### ISSUE TITLE
Unable to install/update 2.3.0 from Netbeans 

### ISSUE THREAD

**Issue by JHag6694** [philippefichet/sonarlint4netbeans#8]
Hello 
When I try to update this plugin from Netbeans 12.0, I get 
   "Networking problem in https://plugins.netbeans.apache.org/catalogue/download//191/sonarlint4netbeans-2.3.0.nbm"
I was able to install it from a downloaded package.

**Comment by philippefichet** [comment]
Hello,
Other plugin installation seem has same issue.
In "https://netbeans.apache.org/nb/plugins/12.0/catalog.xml.gz", many plugin have this double "/" in download url.
I think is an issue for Apache Netbeans ;)

If you want, you can download and install this version manually until this issue is resolved.

**Comment by philippefichet** [comment]
This issue is done in Apache Netbans https://issues.apache.org/jira/browse/NETBEANS-5045.
you can retry but before click to "Check for Updates" to force download "catalog.xml.gz"

**Comment by JHag6694** [comment]
Works fine now.
Merci
